### ISSUE TITLE
1.3.3 does not build

### ISSUE THREAD

**Issue by Rudloff** [httpdispatch/MissedNotificationsReminder#52]
Hello,

I am trying to build 1.3.3 for F-Droid but the Gradle build fails.

It seems the `assembleV14Release` Gradle task does not exist anymore: 
```
Task 'assembleV14Release' not found in project ':app'. Some candidates are: 'assembleRelease'.
```

If I simply run `gradle assembleRelease`, it fails with this error: 
```
Execution failed for task ':app:compileAccessibilityV14ReleaseJavaWithJavac'.
> javax/xml/bind/JAXBException
```

**Comment by httpdispatch** [comment]
Hello

First of all sorry, actual version is 1.3.2 (I've pushed latest commits and created tag)

> It seems the assembleV14Release Gradle task does not exist anymore:

The new flavor dimension has been added to the app to support "Android Go" devices which doesn't have NotificationLIstenerService available

For a now there may be 4 different versions of app:

- API 14 with AccessibilityService - assembleAccessibilityV14Release
- API 18 with NotificationListenerService - assembleNotificationListenerV18Release
- API 27 with AccessibilityService - assembleAccessibilityV27Release (Androig Go low memory devices)
- API 27 with NotificationListenerService - assembleNotificationListenerV27Release

**Comment by Rudloff** [comment]
Thanks for the explanation. I tried to build 1.3.2 with the correct flavors, but I still get this error:
```
Execution failed for task ':app:compileNotificationListenerV18ReleaseJavaWithJavac'.
> javax/xml/bind/JAXBException
```

**Comment by httpdispatch** [comment]
Such as I'm not experiencing this issue (old jdk probably), can you please try a solution from here: https://stackoverflow.com/a/43574427

Add the following dependencies to your build.gradle file:
'''
dependencies {
    // JAX-B dependencies for JDK 9+
    implementation "javax.xml.bind:jaxb-api:2.2.11"
    implementation "com.sun.xml.bind:jaxb-core:2.2.11"
    implementation "com.sun.xml.bind:jaxb-impl:2.2.11"
    implementation "javax.activation:activation:1.1.1"
}
'''

**Comment by httpdispatch** [comment]
If that will help, I'll add it here to repository

**Comment by Rudloff** [comment]
I am using OpenJDK 11.0.4.

I tried to add this:
```diff
diff --git a/app/build.gradle b/app/build.gradle
index 1c44327..8d6280e 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -212,4 +212,9 @@ dependencies {
     testImplementation 'junit:junit:4.12'
     testImplementation 'org.mockito:mockito-core:3.0.0'
     testImplementation 'com.google.truth:truth:1.0'
+
+    implementation "javax.xml.bind:jaxb-api:2.2.11"
+    implementation "com.sun.xml.bind:jaxb-core:2.2.11"
+    implementation "com.sun.xml.bind:jaxb-impl:2.2.11"
+    implementation "javax.activation:activation:1.1.1"
 }
```
But I still get the same error.

**Comment by httpdispatch** [comment]
It looks like the fastest solution for a now is to use JDK 8. I will keep searching for solution for JAVA 9+.

**Comment by httpdispatch** [comment]
Looks like JDK is not supported for android compilation https://issuetracker.google.com/issues/127691113#comment2

**Comment by Rudloff** [comment]
Thanks for investigating this.
Our build server uses OpenJDK 1.8 and manages to build the app so I guess that's good enough.

**Comment by Grossdm** [comment]
Hello, I'd just like to ask about the status of this version/build and F-Droid.
I just looked on F-Droid, and it lists version 1.3.2.0.21 (2010302021).
There is also an older listing of a 1.3.2 version.

Has this been resolved?
Thank you.

**Comment by httpdispatch** [comment]
@Grossdm 1.3.2.x is the latest version https://github.com/httpdispatch/MissedNotificationsReminder/releases

**Comment by Grossdm** [comment]
@httpdispatch, thank you for your prompt response.

Since I use several apps from F-Droid's repo and use the F-Droid app to keep them updated, I'd prefer to continue using your app as provided in their repo.

If you decide (or have decided) not to work with F-Droid to publish (if that's the right term) your app, please let your users know so that they can transition to using GitHub for updates.

Thanks again.

**Comment by httpdispatch** [comment]
> Since I use several apps from F-Droid's repo and use the F-Droid app to keep them updated, I'd prefer to continue using your app as provided in their repo.

Looks like the latest version of the app is already there

> If you decide (or have decided) not to work with F-Droid to publish (if that's the right term) your app, please let your users know so that they can transition to using GitHub for updates.

I am not responsible for the app updates at F-Droid repo. Also, how i know, F-Droid can't update app automatically to the recent version because of multiple flavors present in the app. So once the new version of the app is released somebody should manually update F-Droid.
